/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankie;

/**
 *
 * @author Fariz
 */
public class Home extends javax.swing.JFrame {
int saldo = 50000;
    /**
     * Creates new form Home
     */

    public Home() {
        initComponents();
    }
    public Home(int saldo) {
        this.saldo = saldo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        iSaldo = new javax.swing.JButton();
        Penyetoran = new javax.swing.JButton();
        Bantuan = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Penarikan = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Penyetoran");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 30, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Bantuan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Exit");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Penarikan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 110, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Transfer");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 70, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Informasi Saldo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 30, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 10, 290, 170);

        iSaldo.setText(">");
        iSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(iSaldo);
        iSaldo.setBounds(360, 40, 40, 30);

        Penyetoran.setText("<");
        Penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyetoranActionPerformed(evt);
            }
        });
        getContentPane().add(Penyetoran);
        Penyetoran.setBounds(10, 40, 40, 30);

        Bantuan.setText("<");
        getContentPane().add(Bantuan);
        Bantuan.setBounds(10, 80, 40, 30);

        Exit.setText("<");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(10, 120, 40, 30);

        Penarikan.setText(">");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        getContentPane().add(Penarikan);
        Penarikan.setBounds(360, 120, 40, 30);

        Transfer.setText(">");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(360, 80, 40, 30);

        setSize(new java.awt.Dimension(433, 242));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void PenyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyetoranActionPerformed
        new PenyetoranFrame().show();
        this.dispose();
    }//GEN-LAST:event_PenyetoranActionPerformed

    private void iSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSaldoActionPerformed
        new iSaldoFrame().show();
        this.dispose();
    }//GEN-LAST:event_iSaldoActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        new TransferFrame().show();
        this.dispose();
    }//GEN-LAST:event_TransferActionPerformed

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        
    }//GEN-LAST:event_PenarikanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Penarikan;
    private javax.swing.JButton Penyetoran;
    private javax.swing.JButton Transfer;
    private javax.swing.JButton iSaldo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
