/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankie;

/**
 *
 * @author Fariz
 */
public class iSaldoFrame extends javax.swing.JFrame {

    int saldo = 0;
     
     public iSaldoFrame(int saldo) {
        this.saldo = saldo;
        initComponents();
}
    /**
     * Creates new form iSaldoFrame
     */
    public iSaldoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saldoBox = new javax.swing.JTextField();
        bBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bCek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        saldoBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saldoBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(saldoBox);
        saldoBox.setBounds(20, 50, 170, 30);

        bBack.setText("<< Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack);
        bBack.setBounds(20, 110, 73, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Saldo Anda :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 150, 20);

        bCek.setText("CEK");
        bCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCekActionPerformed(evt);
            }
        });
        getContentPane().add(bCek);
        bCek.setBounds(100, 110, 51, 30);

        setSize(new java.awt.Dimension(233, 188));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        new Home().show();
        this.dispose();
    }//GEN-LAST:event_bBackActionPerformed

    private void bCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCekActionPerformed
        saldoBox.setText("Saldo = Rp" + saldo);
    }//GEN-LAST:event_bCekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iSaldoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iSaldoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iSaldoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iSaldoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iSaldoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bCek;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField saldoBox;
    // End of variables declaration//GEN-END:variables
}
