/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankie;

/**
 *
 * @author Fariz
 */
public class PenyetoranFrame extends javax.swing.JFrame {
int setor = 0, saldo;
String setorShow;

public PenyetoranFrame(int saldo) {
    this.saldo = saldo;
    initComponents();
}
    /**
     * Creates new form PenyetoranFrame
     */
    public PenyetoranFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bSetor = new javax.swing.JButton();
        bBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        b4.setText("Rp 1.000.000");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(20, 170, 190, 30);

        b1.setText("Rp 50.000");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(20, 50, 190, 30);

        b2.setText("Rp 100.000");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(20, 90, 190, 30);

        b3.setText("Rp 500.000");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(20, 130, 190, 30);

        bSetor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bSetor.setText("Setor");
        bSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSetorActionPerformed(evt);
            }
        });
        getContentPane().add(bSetor);
        bSetor.setBounds(100, 220, 110, 30);

        bBack.setText("<< Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });
        getContentPane().add(bBack);
        bBack.setBounds(20, 220, 73, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 190, 20);

        setSize(new java.awt.Dimension(245, 304));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        setor = 50000;
        setorShow="Rp 50.000";
        jLabel1.setText("Anda menyetorkan Rp 50.000");
        
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        setor = 100000;
        setorShow="Rp 100000";
        jLabel1.setText("Anda menyetorkan Rp 100.000");
        
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        setor = 500000;
        setorShow="Rp 500000";
        jLabel1.setText("Anda menyetorkan Rp 500.000");
        
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        setor = 1000000;
        setorShow="Rp 1000000";
        jLabel1.setText("Anda menyetorkan Rp 1.000.000");
        
        
        b1.setEnabled(false);
        b2.setEnabled(false);
        b3.setEnabled(false);
        b4.setEnabled(false);
    }//GEN-LAST:event_b4ActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        new Home().show();
        this.dispose();
        setor = 0;
    }//GEN-LAST:event_bBackActionPerformed

    private void bSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSetorActionPerformed
        saldo = saldo + setor;
        javax.swing.JOptionPane.showMessageDialog(null,"Penyetoran Berhasil ! \n Saldo Anda Sekarang = Rp "+saldo);
    }//GEN-LAST:event_bSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bSetor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
